/* Demo dataset — fictional/mock application data, NOT live market data,
   NOT financial advice. Swapped out as real backend endpoints land. */

window.DemoData = (() => {
  const hoursAgo = (h) => new Date(Date.now() - h * 3600 * 1000).toISOString();

  const stocks = [
    {
      symbol: 'RELIANCE',
      companyName: 'Reliance Industries',
      exchange: 'NSE',
      sector: 'Energy',
      description: 'Conglomerate with energy, retail and telecom interests.',
      price: 2912.4,
      change: 34.6,
      changePct: 1.2,
    },
    {
      symbol: 'TCS',
      companyName: 'Tata Consultancy Services',
      exchange: 'NSE',
      sector: 'Technology',
      description: 'IT services and consulting giant.',
      price: 4210.0,
      change: -18.2,
      changePct: -0.43,
    },
    {
      symbol: 'INFY',
      companyName: 'Infosys',
      exchange: 'NSE',
      sector: 'Technology',
      description: 'Global digital services and consulting company.',
      price: 1568.75,
      change: 11.4,
      changePct: 0.73,
    },
    {
      symbol: 'HDFCBANK',
      companyName: 'HDFC Bank',
      exchange: 'NSE',
      sector: 'Financials',
      description: 'Leading private sector bank.',
      price: 1684.35,
      change: 6.9,
      changePct: 0.41,
    },
    {
      symbol: 'ICICIBANK',
      companyName: 'ICICI Bank',
      exchange: 'NSE',
      sector: 'Financials',
      description: 'Private sector bank with strong retail franchise.',
      price: 1283.5,
      change: 21.4,
      changePct: 1.7,
    },
    {
      symbol: 'SBIN',
      companyName: 'State Bank of India',
      exchange: 'NSE',
      sector: 'Financials',
      description: 'Largest public sector bank in India.',
      price: 822.15,
      change: -4.05,
      changePct: -0.49,
    },
    {
      symbol: 'ITC',
      companyName: 'ITC Limited',
      exchange: 'NSE',
      sector: 'Consumer',
      description: 'Diversified conglomerate spanning FMCG, hotels and agri.',
      price: 486.6,
      change: 2.3,
      changePct: 0.47,
    },
    {
      symbol: 'TATASTEEL',
      companyName: 'Tata Steel',
      exchange: 'NSE',
      sector: 'Materials',
      description: "One of the world's top steel producers.",
      price: 154.9,
      change: 4.6,
      changePct: 3.06,
    },
    {
      symbol: 'BHARTIARTL',
      companyName: 'Bharti Airtel',
      exchange: 'NSE',
      sector: 'Telecom',
      description: 'Global telecommunications services company.',
      price: 1547.4,
      change: -7.8,
      changePct: -0.5,
    },
    {
      symbol: 'HINDUNILVR',
      companyName: 'Hindustan Unilever',
      exchange: 'NSE',
      sector: 'Consumer',
      description: 'FMCG leader across home and personal care products.',
      price: 2590.7,
      change: -12.3,
      changePct: -0.47,
    },
  ];

  const posts = [
    {
      id: 'p1',
      author: 'sahiltrades',
      stockSymbol: 'TATASTEEL',
      title: 'Possible breakout above resistance',
      body: 'Tata Steel has been consolidating in a tight range for six weeks. Volume on the last three sessions has picked up while the range tightened — classic coil setup. A close above 158 on strong volume could open the path toward 172. Risk: the whole metals complex remains sensitive to China demand data.',
      comments: 12,
      upvotes: 42,
      downvotes: 7,
      createdAt: hoursAgo(2),
      status: 'ACTIVE',
    },
    {
      id: 'p2',
      author: 'vikram__rm',
      stockSymbol: 'INFY',
      title: 'Margin story is finally turning',
      body: 'QoQ margin expansion of 90bps was the headline, but attrition claims and the large-deal pipeline deserve attention. If the 6%+ guided growth materializes, this re-rating has room to run. Watch the 1550 support zone.',
      comments: 8,
      upvotes: 27,
      downvotes: 3,
      createdAt: hoursAgo(5),
      status: 'ACTIVE',
    },
    {
      id: 'p3',
      author: 'priya_invests',
      stockSymbol: 'SBIN',
      title: 'PSU lenders — yield chasing or fundamentals?',
      body: 'Everyone piles into PSU banks when the yield curve steepens. The risk is the "one big trade" crowding. SBI\'s deposit franchise is real, but don\'t mistake beta for alpha. Fundamentals still matter at these valuations.',
      comments: 19,
      upvotes: 63,
      downvotes: 12,
      createdAt: hoursAgo(9),
      status: 'ACTIVE',
    },
    {
      id: 'p4',
      author: 'desi_value',
      stockSymbol: 'ITC',
      title: 'ITC hotels: the underappreciated optionality',
      body: 'The market values the FMCG book and ignores the hotel portfolio. That is a free option on the India travel cycle. Slow and boring, but the margin trajectory is quietly improving every quarter.',
      comments: 6,
      upvotes: 18,
      downvotes: 1,
      createdAt: hoursAgo(15),
      status: 'ACTIVE',
    },
    {
      id: 'p5',
      author: 'chart_ravi',
      stockSymbol: 'RELIANCE',
      title: 'Retail demerger math',
      body: "Throwing a few numbers at the retail demerger: listed peers trade at ~6x EV/Sales. Apply that to Reliance Retail's revenue and the stub math suggests the parent is getting the retail business nearly free. Check my numbers.",
      comments: 31,
      upvotes: 88,
      downvotes: 21,
      createdAt: hoursAgo(22),
      status: 'ACTIVE',
    },
    {
      id: 'p6',
      author: 'sahiltrades',
      stockSymbol: 'HDFCBANK',
      title: 'Why I am waiting for the base to build',
      body: 'HDFC Bank has repaired its loan book but the stock needs time to rebuild its base. A year of consolidation is not a tragedy when you get paid dividend while you wait. Patience is a position.',
      comments: 4,
      upvotes: 9,
      downvotes: 5,
      createdAt: hoursAgo(30),
      status: 'ACTIVE',
    },
    {
      id: 'p7',
      author: 'mod_mechanic',
      stockSymbol: 'ICICIBANK',
      title: 'Best-in-class delivery on capital ratios',
      body: 'CET-1 above 17% plus a solid loan growth engine. ICICI keeps executing when peers stumble. The RR curve on this one is the cleanest in the private bank pack right now.',
      comments: 14,
      upvotes: 39,
      downvotes: 6,
      createdAt: hoursAgo(45),
      status: 'ACTIVE',
    },
    {
      id: 'p8',
      author: 'gamma_god',
      stockSymbol: 'BHARTIARTL',
      title: 'ARPU upcycle thesis — still intact?',
      body: 'Premium mix is doing the heavy lifting while rural ARPU lags. The question is whether the next tariff hike lands in the next two quarters. If yes, expect the Street to re-rate the multiple.',
      comments: 10,
      upvotes: 24,
      downvotes: 8,
      createdAt: hoursAgo(52),
      status: 'ACTIVE',
    },
    {
      id: 'p9',
      author: 'hidden_hand',
      stockSymbol: 'TCS',
      title: 'Hidden post — moderation sample',
      body: 'This post is hidden and must not appear in public feeds.',
      comments: 0,
      upvotes: 0,
      downvotes: 0,
      createdAt: hoursAgo(60),
      status: 'HIDDEN',
    },
  ];

  const comments = [
    {
      id: 'c1',
      postId: 'p1',
      author: 'nifty_nomad',
      body: '158 close is the line in the sand. Printed a decent double bottom on the hourly.',
      createdAt: hoursAgo(1.6),
    },
    {
      id: 'c2',
      postId: 'p1',
      author: 'sahiltrades',
      body: 'Agreed — and I would respect the 148 stop. Metals are whippy.',
      createdAt: hoursAgo(1.4),
    },
    {
      id: 'c3',
      postId: 'p1',
      author: 'delta_dash',
      body: 'China property data next week is the real catalyst.',
      createdAt: hoursAgo(1.1),
    },
    {
      id: 'c4',
      postId: 'p1',
      author: 'yieldyogi',
      body: 'Volume pick-up on a breakout attempt matters more than price alone here.',
      createdAt: hoursAgo(0.7),
    },
    {
      id: 'c5',
      postId: 'p3',
      author: 'bankroll_ben',
      body: 'Funding cost pressure is under-appreciated. Net interest margins could compress.',
      createdAt: hoursAgo(8),
    },
    {
      id: 'c6',
      postId: 'p3',
      author: 'priya_invests',
      body: 'Exactly — that is why I said the deposit franchise, not the loan book, is the moat.',
      createdAt: hoursAgo(8.5),
    },
  ];

  const ideas = [
    {
      id: 'i1',
      author: 'sahiltrades',
      stockSymbol: 'INFY',
      direction: 'BULLISH',
      entryPrice: 1565,
      targetPrice: 1685,
      stopLossPrice: 1505,
      thesis: 'Margin recovery plus a strong large-deal pipeline; stop below the recent swing low.',
      status: 'OPEN',
      createdAt: hoursAgo(10),
    },
    {
      id: 'i2',
      author: 'desi_value',
      stockSymbol: 'ITC',
      direction: 'BULLISH',
      entryPrice: 478,
      targetPrice: 525,
      stopLossPrice: 462,
      thesis:
        'Hotels optionality repricing with steady FMCG dividend. Low-risk long for a patient horizon.',
      status: 'OPEN',
      createdAt: hoursAgo(26),
    },
    {
      id: 'i3',
      author: 'chart_ravi',
      stockSymbol: 'TATASTEEL',
      direction: 'BULLISH',
      entryPrice: 152,
      targetPrice: 172,
      stopLossPrice: 143,
      thesis:
        'Range breakout with ascending volume; trade only on a confirmed close above resistance.',
      status: 'HIT_TARGET',
      createdAt: hoursAgo(120),
    },
    {
      id: 'i4',
      author: 'gamma_god',
      stockSymbol: 'BHARTIARTL',
      direction: 'BEARISH',
      entryPrice: 1560,
      targetPrice: 1480,
      stopLossPrice: 1605,
      thesis:
        'Premium mix stalled while valuation pricing in an aggressive tariff upcycle. Short the multiple.',
      status: 'OPEN',
      createdAt: hoursAgo(18),
    },
    {
      id: 'i5',
      author: 'mod_mechanic',
      stockSymbol: 'RELIANCE',
      direction: 'NEUTRAL',
      entryPrice: 2905,
      targetPrice: 3120,
      stopLossPrice: 2760,
      thesis:
        'Demerger outcome is binary; prefer a tight range and wait for the record date clarity.',
      status: 'EXPIRED',
      createdAt: hoursAgo(260),
    },
  ];

  const watchlists = [
    { id: 'w1', name: 'My Stocks', stocks: ['TATASTEEL', 'INFY', 'RELIANCE'] },
    { id: 'w2', name: 'Long Term', stocks: ['HDFCBANK', 'ITC', 'HINDUNILVR', 'TCS'] },
    { id: 'w3', name: 'Watch Closely', stocks: ['SBIN', 'ICICIBANK', 'BHARTIARTL'] },
  ];

  const indices = [
    { name: 'NIFTY 50', value: 24580.4, change: 156.2, changePct: 0.64 },
    { name: 'SENSEX', value: 80640.1, change: 420.8, changePct: 0.52 },
    { name: 'BANK NIFTY', value: 52340.6, change: -85.3, changePct: -0.16 },
    { name: 'INDIA VIX', value: 13.42, change: -0.61, changePct: -4.35 },
  ];

  return { stocks, posts, comments, ideas, watchlists, indices };
})();
